### PR TITLE
Fixed cors and non-batch requests errors (#13)

### LINKED ISSUE #13: Preflight and non-batching requests throw an error
The generated custom http handler does not handle preflight requests and cors headers. It also always returns response in a batch (as a json array) even when a single GraphQL request is sent. 

[Cors](https://github.com/rs/cors) is a good library to handle cors headers & preflight requests. This, however, will add additional dependency for a user who's using the custom generated http handler.

### PR DESCRIPTION
**Pull request by 0xSalman**
Closes #13 

## Test Notes

1. `make install build`
1. `make run-sample`
1. Send a preflight request to sample GraphQL server and verify it does not throw an error
1. Send a single GraphQL request to sample server and verify it returns a single json object

Sample Requests

```
1. Request 
curl -XOPTIONS localhost:7050/graphql -H "Content-Type: application/graphql" \ 
-H "Access-Control-Request-Method: POST" \
-d '{ person(id: "1000") { name email friends { name email } } }'

Expected Response
200 OK

2. Request
curl -XPOST localhost:7050/graphql -H "Content-Type: application/graphql" \
-d '{ person(id: "1000") { name email friends { name email } } }'

Expected Response
{
  "data": {
    "person": {
      "name": "Luke Skywalker",
      "email": "luke.skywalker@star.wars",
      "friends": [
        {
          "name": "Han Solo",
          "email": "han.solo@star.wars"
        },
        {
          "name": "Leia Organa",
          "email": "leia.organa@star.wars"
        }
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by SteveGBanton** [comment]
The POST request is generating expected response, but the OPTIONS request is returning "GraphQL only supports POST and GET requests."

**Comment by 0xSalman** [comment]
Update first sample request. It was missing `Access-Control-Request-Method: POST` header

**Comment by SteveGBanton** [comment]
OK, works for me

**Review by edlau — APPROVED** [review]
Visually inspected.

**Pull request merged**
